# Strapi用のDockerfile

# Node.js 20ベースのイメージ
FROM node:20-alpine

# 必要なライブラリをインストール
RUN apk add --no-cache libc6-compat

# 作業ディレクトリを設定
WORKDIR /srv/app

# パッケージファイルをコピー
COPY cms/package.json cms/package-lock.json ./

# sharpモジュールのインストールを行う際に正しいアーキテクチャを指定
RUN npm install --platform=linuxmusl --arch=arm64v8 sharp

# 残りの依存関係をインストール
RUN npm install

# ソースコードをコピー
COPY cms .

# 環境変数の設定
ENV NODE_ENV=production

# ポートを開放
EXPOSE 1337

# アプリケーションの起動
CMD ["npm", "start"]
