# Production image
FROM node:20-alpine

# 必要なライブラリをインストール
RUN apk add --no-cache libc6-compat python3 make g++ bash vips vips-dev

# 作業ディレクトリを設定
WORKDIR /srv/app

# パッケージファイルをコピー
COPY cms/package.json cms/package-lock.json ./

# 依存関係をインストール
RUN npm ci

# ソースコードをコピー
COPY cms/ .

# アプリケーションをビルド
RUN npm run build

# 環境変数の設定
ENV NODE_ENV=production

# ポートを開放
EXPOSE 1337

# アプリケーションの起動
CMD ["npm", "start"]
