services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./next:/app

  strapi:
    build:
      context: .
      dockerfile: Dockerfile.cms
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
    volumes:
      - ./cms:/srv/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
